market-owner:
  name-pattern: ^.+ИП|^.+ООО|^.+ПАО|^.+ЗАО|^.+МУП|^.+ГБУ
  name-Pattern: t
  test: 1

spring:
  datasource:
    generate-unique-name: false
    name: creatorcloud
  jpa:
    show-sql: true
rest:
  base-path: /data-api
server:

  port: 60001
logging:
  level:
    root: WARN
    org.springframework.security: DEBUG



